# Generated by Django 4.2.6 on 2023-11-06 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='image/')),
                ('pdis1', models.TextField()),
                ('image2', models.ImageField(upload_to='image/')),
                ('ptitle', models.CharField(max_length=100)),
                ('pdis2', models.TextField()),
                ('pcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cat')),
            ],
        ),
    ]
