# Generated by Django 4.2.6 on 2023-11-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='total_views',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(max_length=10)),
                ('pid', models.IntegerField(max_length=10)),
            ],
        ),
    ]
